version: '2.2'
services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
