version: '2.2'
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./docker/php/php.override.ini:/usr/local/etc/php/conf.d/php.override.ini
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
